-- 기존에 있던 테이블들 지우는 sql
--DROP TABLE "TBL_MEMBER" CASCADE CONSTRAINTS;
--DROP TABLE "TBL_COMMUNITY_CATEGORY" CASCADE CONSTRAINTS;
--DROP TABLE "TBL_COMMUNITY" CASCADE CONSTRAINTS;
--DROP TABLE "TBL_COMMUNITY_COMMENT" CASCADE CONSTRAINTS;
--DROP TABLE "TBL_STUDYCAFE" CASCADE CONSTRAINTS;
--DROP TABLE "TBL_STUDYCAFEIMG" CASCADE CONSTRAINTS;
--DROP TABLE "TBL_STUDYININFO" CASCADE CONSTRAINTS;
--DROP TABLE "TBL_STUDYINPARE" CASCADE CONSTRAINTS;
--DROP TABLE "TBL_STUDYGINFO" CASCADE CONSTRAINTS;
--DROP TABLE "TBL_STUDYREVIEW" CASCADE CONSTRAINTS;
--DROP TABLE "TBL_STUDYGIMG" CASCADE CONSTRAINTS;
--DROP TABLE "TBL_STUDYGPARE" CASCADE CONSTRAINTS;
--DROP TABLE "TBL_MEMBERININFO" CASCADE CONSTRAINTS;
--DROP TABLE "TBL_TOGETHERSTUDY" CASCADE CONSTRAINTS;
--DROP TABLE "TBL_STUDYGORDER" CASCADE CONSTRAINTS;

-- 테이블 생성


-- 시퀀스
-- Tbl_Member_Alarm , MAIdx
CREATE SEQUENCE c##snake2.MAlarm_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_MemberLog, MLogIdx
CREATE SEQUENCE c##snake2.MLog_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_Community, ComIdx
CREATE SEQUENCE c##snake2.Community_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_Community_Comment, CCIdx
CREATE SEQUENCE c##snake2.ComComment_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_Community_Category, ComCateIdx
CREATE SEQUENCE c##snake2.ComCategory_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_StudyInInfo, SeatNum
CREATE SEQUENCE c##snake2.SIInfo_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_StudyInPare, SIPIdx
CREATE SEQUENCE c##snake2.SInpare_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_StudyCafe, SCIdx
CREATE SEQUENCE c##snake2.StudyCafe_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_StudyCafeImg, SCImgIdx
CREATE SEQUENCE c##snake2.SCafeImg_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_StudyGInfo, SGIIdx
CREATE SEQUENCE c##snake2.SGInfo_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_StudyGPare, SGPIdx
CREATE SEQUENCE c##snake2.SGPare_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_StudyGImg, SGImgIdx
CREATE SEQUENCE c##snake2.SGImg_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_StudyReview, SRIdx
CREATE SEQUENCE c##snake2.SReview_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_StudyReviewComment, TSRCIdx
CREATE SEQUENCE c##snake2.SRComment_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_StudyReviewCommentlike, TSRCLIdx
CREATE SEQUENCE c##snake2.SRCommentLike_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_StudyReviewMemberTag, TSRMIdx
CREATE SEQUENCE c##snake2.SRMemberTag_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_StudyHasTag, TSHTIdx
CREATE SEQUENCE c##snake2.SHasTag_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_StudyHasTagList, TSHTLIdx
CREATE SEQUENCE c##snake2.SHasTagList_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_StudyReviewLike, TSRLidx
CREATE SEQUENCE c##snake2.SRLike_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;

-- Tbl_StudyReviewImg, SRIImgIdx
CREATE SEQUENCE c##snake2.ComCom_seq
   INCREMENT BY 1
   START WITH 1
   MINVALUE 1
   MAXVALUE 9999
   NOCYCLE
   NOCACHE
   NOORDER;